<?php

/**
 * Implements hook theme.
 */
function beetroot_example_theme($existing, $type, $theme, $path) {
  return [
    'beetroot_example_news' => [
      'variables' => [
        'title' => NULL,
        'content' => NULL,
        'links' => NULL,
      ],
    ],
    'beetroot_example_news_link' => [
      'variables' => [
        'url' => NULL,
        'title' => NULL,
      ],
    ],
  ];
}
