<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

function beetroot_example_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($operation == 'view' && $entity->getEntityTypeId() == 'node') {
    return AccessResult::forbiddenIf($account->isAnonymous());
  }
  return AccessResult::neutral();
}
