image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - test

build:
  stage: build
  script:
    - cp .env.dist .env
    - docker-compose pull
    - docker-compose up -d --build --remove-orphans

test:
  stage: test
  script:
    - docker ps