image: tmaier/docker-compose:latest

services:
  - docker:dind

# .pre:
#   stage: .pre
#   script:
#     - cp .env.dist .env

build image:
  stage: build
  script:
    - cp .env.dist .env
    - docker-compose pull
    - docker-compose up -d --build --remove-orphans

test:
  stage: test
  script:
    - docker-compose exec -T php composer install --no-interaction

#deploy, .post