image:
  name: docker:latest
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

# .pre:
#   stage: .pre
#   script:
#     - cp .env.dist .env

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up -d

# build image:
#   stage: build
#   script:
#     - cp .env.dist .env
#     - docker-compose pull
#     - docker-compose up -d --build --remove-orphans

# test:
#   stage: test
#   script:
#     - docker-compose exec -T php composer install --no-interaction

#deploy, .post