image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

build image:
  stage: build
  script:
    - cp .env.dist .env
    - docker-compose pull
    - docker-compose up -d --build --remove-orphans

test:
  stage: test
  script:
    - docker-compose exec -T --user=root php bash -c 'chown -R www-data:www-data /var/www'