image: tmaier/docker-compose:latest

stages:
  - .pre
  - build
  - test
  - deploy
  - .post

# services:
#   - docker:dind

services:
  - name: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    alias: elasticsearch
    entrypoint: ["/bin/bash"]
    command: ["-c", "env discovery.type=single-node ES_JAVA_OPTS='-Xms64m -Xmx64m' xpack.security.enabled=false es-docker"]

# before_script:
#   - docker info
#   - docker-compose --version

.pre:
  stage: .pre
  script:
    - echo ".pre"
    - cp .env.dist .env

build:
  stage: build
  script:
    - docker-compose build
    # - docker-compose pull
    # - docker-compose up -d --build --remove-orphans

test:
  stage: test
  script:
    - echo "test"
    # - docker-compose exec -T php composer install --no-interaction

deploy:
  stage: deploy
  script:
    - echo "deploy"

.post:
  stage: .post
  script:
    - echo ".post"