image: docker/compose:latest

services:
  - docker:dind

stages:
  - .pre
  - build
  - test
  - deploy
  - .post

.pre:
  stage: .pre
  script:
    - echo ".pre"
    - cp .env.dist .env

build:
  stage: build
  script:
    - echo "build"
    # - docker-compose build
    # - docker-compose pull
    # - docker-compose up -d --build --remove-orphans

test:
  stage: test
  script:
    - echo "test"
    # - docker-compose exec -T php composer install --no-interaction

deploy:
  stage: deploy
  script:
    - echo "deploy"

.post:
  stage: .post
  script:
    - echo ".post"