image: node:10.15.3

pipelines:
  default:
    - step:
        name: 'run tests'
        script:
          - docker-compose -v
          - docker-compose run app npm run test
          - echo 'tests done'
        services:
          - docker

definitions:
    services:
        docker:
            image: docker/compose:1.25.4