image: docker:latest

pipelines:
  default:
    - step:
        script:
        - cp .env.dist .env
    - step:
        script:
        - echo "Hello"
    - step:
        script:
          - docker version
        services:
        - docker
        image: php:8.1
        caches:
        - composer
        # script:
        # - docker-compose up -d
    # - step:
    #     script:
    #     - docker-compose exec -T --user=root php bash -c 'chown -R www-data:www-data /var/www'

options:
  docker: true