image: atlassian/default-image:latest

options:
  docker: true

pipelines:
  default:
    - step:
        name: "1"
        script:
        - apt-get update
        - apt-get install
        - docker version
    - step:
        name: "2"
        script:
        - docker build .