image: docker/compose:1.25.4
pipelines:
  default:
    - step:
        name: 'docker-compose -v'
        script:
          - docker-compose -v
    - step:
        name: 'docker-compose build'
        script:
          - docker-compose build
        services:
          - docker
    - step:
        name: 'docker-compose up'
        script:
          - docker-compose up
        services:
          - docker