image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: "1"
        script:
        - apt-get update
        - apt-get install docker-compose
        - docker compose version
    - step:
        name: "2"
        script:
        - docker-compose up -d

options:
  docker: true