image: ubuntu:latest

pipelines:
  default:
    - step:
        script:
          - pip3 install docker-compose
    - step:
        script:
          - echo "Hello"
    - step:
        script:
        - docker-compose up -d