image: docker/compose:1.25.4
pipelines:
  default:
    - step:
        name: 'docker-compose -v'
        script:
          - docker-compose -v
          - docker-compose build
    - step:
        name: 'docker-compose build'
        script:
          - docker-compose up -d --build

        services:
          - docker