image: ubuntu:20.04

pipelines:
  default:
    - step:
        name: 'install and run tests'
        script:
          - docker build -t myapp .
          - docker run --entrypoint="" myapp npm run test
          - echo 'done!'
        services:
          - postgres
          - docker