image: ubuntu:20.04

pipelines:
  default:
    - step:
        name: 'install docker-compose, and run tests'
        script:
          - curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          - chmod +x /usr/local/bin/docker-compose
          - docker-compose -v
          - docker-compose run app npm run test
          - echo 'tests done'
        services:
          - docker