image: docker:latest

pipelines:
  default:
    - step:
        script:
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        - composer install
        - vendor/bin/phpunit --testsuite unit,integration
        artifacts:
        - vendor
    #     script:
    #     - cp .env.dist .env
        # - apt-get install python3-pip
        # - pip install docker-compose
    - step:
        script:
        - echo "Hello"
    - step:
        script:
        - docker-compose up -d
    - step:
        script:
        - docker-compose exec -T --user=root php bash -c 'chown -R www-data:www-data /var/www'