image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: "DC"
        script:
        - apt-get update
        - apt-get install docker-compose-plugin
    - step:
        name: "DC"
        script:
          - docker-compose up -d

options:
  docker: true