image: atlassian/default-image:latest

options:
  docker: true

pipelines:
  default:
    - step:
        name: "1. Prepare"
        script:
        - apt-get update
        - apt-get install
        - docker version
    - step:
        name: "2. Build"
        script:
        - docker build .