image: docker:stable

options:
  docker: true

pipelines:
  default:
    - step:
        name: "pip"
        script:
          - pip install -U
    - step:
        name: "dependencies"
        script:
          - sh ci/dependencies.sh
    - step:
        name: "docker-compose run"
        script:
          - docker-compose run -T client /usr/local/src/test.sh
    - step:
        name: "docker-compose down"
        script:
          - docker-compose down