image: docker/compose:1.25.4
pipelines:
  default:
    - step:
        name: 'run tests'
        script:
          - docker-compose -v
          - docker-compose build
          - echo 'tests done'
        services:
          - docker