image: docker:latest

pipelines:
  default:
    # - step:
    #     script:
    #     - cp .env.dist .env
    - step:
        script:
        - echo "Hello"
    - step:
        script:
        - apt-get update && apt-get install -y unzip
    - step:
        script:
        - docker-compose up -d
    - step:
        script:
        - docker-compose exec -T --user=root php bash -c 'chown -R www-data:www-data /var/www'