version: "3"

services:
  php:
    build: .
    working_dir: '/var/www'
    volumes:
      - './:/var/www:cached'
    env_file:
      - ./.env
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/vendor/bin
    hostname: ${PROJECT_BASE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(\"${PROJECT_BASE_URL}\")"
      - "traefik.http.services.php.loadbalancer.server.port=80"
      - "traefik.http.routers.php.entrypoints=web"
      - "traefik.http.routers.php.middlewares=redirect-to-https"  # Redirect HTTP to HTTPS
      - "traefik.http.routers.php-secure.rule=Host(\"${PROJECT_BASE_URL}\")"
      - "traefik.http.routers.php-secure.entrypoints=websecure"
      - "traefik.http.routers.php-secure.tls.certresolver=myresolver"

  database:
    image: mariadb
    volumes:
      - my-datavolume:/var/lib/mysql
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=${MYSQL_DB_NAME}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASS}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(\"phpmyadmin.${PROJECT_BASE_URL}\")"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.routers.phpmyadmin.middlewares=redirect-to-https"
      - "traefik.http.routers.phpmyadmin-secure.rule=Host(\"phpmyadmin.${PROJECT_BASE_URL}\")"
      - "traefik.http.routers.phpmyadmin-secure.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin-secure.tls.certresolver=myresolver"

  traefik:
    image: "traefik:v2.6"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=sergiikostanets@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      # Middleware to redirect non-www to www
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https?://(.*)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.$${1}"
      # Middleware to force HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Router for HTTP to HTTPS redirection
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # Router for HTTPS redirection to www
      - "traefik.http.routers.https-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.https-catchall.entrypoints=websecure"
      - "traefik.http.routers.https-catchall.middlewares=redirect-to-www"
      - "traefik.http.routers.https-catchall.tls=true"
      - "traefik.http.routers.https-catchall.tls.certresolver=myresolver"
      # Router for the actual service
      - "traefik.http.routers.php.rule=Host(`www.${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.php.entrypoints=websecure"
      - "traefik.http.routers.php.tls=true"
      - "traefik.http.routers.php.tls.certresolver=myresolver"

  node:
    image: node:slim
    user: "node"
    environment:
      - NODE_ENV=development
      - SHELL=bash
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app/web/themes/custom/beetroot_example_theme
    command: sh -c "npm ci && npm run build"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(\"node.${PROJECT_BASE_URL}\")"
      - "traefik.http.services.node.loadbalancer.server.port=3000"

volumes:
  my-datavolume:
  letsencrypt:
