beetroot_example.settings:
  type: config_object
    label: 'Beetroot Example Settings'
    mapping:
      enabled:
        type: boolean
        label: 'Enabled'
      number:
        type: integer
        label: 'Some important number'
      text:
        type: string
        label: 'Some text'
