_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
langcode: ru
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  standard__front_page:
    weight: -46
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  example_page:
    weight: -45
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
  latest_news__content:
    weight: -48
    parent: ''
    menu_name: main
    enabled: true
    expanded: false
  sort_news__content:
    weight: -44
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
