# Schema for the configuration files of the Beetroot Example module.
beetroot_example.settings:
  type: config_object
  label: 'Beetroot Example settings'
  mapping:
    example:
      type: string
      label: 'Example'

beetroot_example.text_cleanup.settings:
  type: config_object
  label: 'Beetroot Example Cleanup plugin settings'
  mapping:
    example:
      type: string
      label: 'Example'

beetroot_example.beetroot_example.*:
  type: config_entity
  label: Beetroot Example
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    type:
      type: string
      label: Type
    plugins:
      type: sequence
      label: 'Plugins'
      sequence:
        type: string
        label: 'Plugin'
