<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function glossary_tooltip_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (!$entity instanceof NodeInterface
    || !$entity->hasField('body')
    || $entity->get('body')->isEmpty()
  ) {
    return;
  }

  $body = $entity->get('body')->value;
  $termStorage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');

  $ids = $termStorage->getQuery()
    ->condition('vid', 'glossary')
    ->execute();

  $vocabulary = [];
  foreach ($termStorage->loadMultiple($ids) as $item) {
    $vocabulary[$item->id()] = [
      "id" => $item->id(),
      "name" => $item->label(),
      "body" => $item->get("description")->value,
    ];
  }

  foreach ($vocabulary as $taxonomy) {
    $description = strip_tags($taxonomy["body"], $allowed_tags = NULL);
    $term = $taxonomy["name"];

    if (strlen($description) >= 100) {
      $description = substr($description, 0, 100);
      $description .= '... Read more!';
    }

    $body = str_replace($term, "<a title=\"$description\" href=\"/taxonomy/term/{$taxonomy["id"]}\">$term</a>", $body);
  }

  if ($build['#view_mode'] == 'full' && isset($build['body'])) {
    $build['body'] = [
      '#type' => 'container',
      '#weight' => 5,
      '#attributes' => [
        'class' => ['body_glossary_tooltip'],
      ],
    ];
    $build['body']['p'] = [
      '#type' => 'html_tag',
      '#tag' => 'p',
      '#value' => $body,
    ];
  }
  return $build;
}
